### ISSUE TITLE
Can't read mcstructure file (it is nbt file)

### ISSUE THREAD

**Issue by phamtuongvan** [spnda/dart_minecraft#5]
Bedrock .mcstructure files structure https://gist.github.com/tryashtar/87ad9654305e5df686acab05cc4b6205

**Comment by spnda** [comment]
I think this is because Bedrock NBT uses little endianness. I will look to see if I can detect or make some additions to the API for endianness. Thanks for the report.

**Comment by spnda** [comment]
I've changed the API slightly so you can now do the following:
```dart
var reader = NbtReader.fromFile(file.path);
reader.setEndianness = Endian.little; // Depends whether Java or Bedrock
reader.read();
```
The same can be done with NbtWriter. Detecting the endianness is nearly impossible and can't be done accurately with NBT files. You will need to "guess" based on what NBT file it is.

Thank you for your issue!
